import type { JsonObject } from "./types/json.js";
import { isPlainObject } from "./types/json.js";

const MAX_EDGE_LABEL_LEN = 96;

/** Escape text for Mermaid edge labels (stateDiagram-v2). */
function escapeEdgeLabel(s: string): string {
  let t = s
    .replace(/"/g, "'")
    .replace(/\|/g, "/")
    .replace(/\n/g, " ")
    .replace(/;/g, ",")
    .replace(/[—–]/g, " - ")
    .trim();
  if (t.length > MAX_EDGE_LABEL_LEN) t = `${t.slice(0, MAX_EDGE_LABEL_LEN - 1)}…`;
  return t;
}

function escapeStateDisplayName(stateKey: string): string {
  return stateKey.replace(/"/g, '\\"');
}

function formatConditions(conditions: unknown): string | null {
  if (!Array.isArray(conditions) || conditions.length === 0) return null;
  const parts = conditions.map((c) => (typeof c === "string" ? c : JSON.stringify(c)));
  const joined = parts.join(", ");
  if (joined.length > 80) return `${joined.slice(0, 77)}…`;
  return joined;
}

/** Stable Mermaid vertex ids (no quotes on edges — avoids parsers that join lines). */
function buildVertexIdMap(stateKeys: Iterable<string>): Map<string, string> {
  const map = new Map<string, string>();
  const used = new Set<string>();
  for (const key of stateKeys) {
    let slug = key.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
    if (!slug) slug = "state";
    if (/^[0-9]/.test(slug)) slug = `s_${slug}`;
    let id = `v_${slug}`;
    let n = 2;
    while (used.has(id)) {
      id = `v_${slug}_${n++}`;
    }
    used.add(id);
    map.set(key, id);
  }
  return map;
}

interface EdgeRow {
  from: string;
  to: string;
  label: string;
}

/**
 * Build Markdown with a Mermaid stateDiagram-v2 from Stubber `states` and
 * action `to_state` maps. Returns null if there is no `states` object.
 */
export function renderWorkflowFsmMarkdown(root: JsonObject): string | null {
  if (!isPlainObject(root.states)) return null;

  const states = root.states as JsonObject;
  const actions = isPlainObject(root.actions) ? (root.actions as JsonObject) : {};
  const details = isPlainObject(root.details) ? (root.details as JsonObject) : null;
  const start =
    details && typeof details.busy_start_state === "string" ? details.busy_start_state : null;

  const edgeList: EdgeRow[] = [];
  const unknownActions: string[] = [];

  for (const stateKey of Object.keys(states)) {
    const st = states[stateKey];
    if (!isPlainObject(st)) continue;
    const allowed = st.actions;
    if (!Array.isArray(allowed)) continue;

    for (const raw of allowed) {
      if (typeof raw !== "string") continue;
      const actionName = raw;
      const action = actions[actionName];
      if (!isPlainObject(action)) {
        unknownActions.push(`${stateKey} → ? (${actionName})`);
        continue;
      }
      const toState = action.to_state;
      if (!isPlainObject(toState) || Object.keys(toState).length === 0) continue;

      for (const [branchKey, tval] of Object.entries(toState)) {
        if (!isPlainObject(tval)) continue;
        const target =
          typeof tval.state === "string" && tval.state.length > 0 ? tval.state : branchKey;
        const cond = formatConditions(tval.conditions);
        const isDefault =
          isPlainObject(tval.meta) && (tval.meta as JsonObject).default === true;
        let label = actionName;
        if (isDefault) label += " (default)";
        if (cond && cond !== "true") label += ` - if ${cond}`;
        const safeLabel = escapeEdgeLabel(label);
        edgeList.push({ from: stateKey, to: target, label: safeLabel });
      }
    }
  }

  const allKeys = new Set<string>(Object.keys(states));
  for (const e of edgeList) {
    allKeys.add(e.from);
    allKeys.add(e.to);
  }
  if (start) allKeys.add(start);

  const vertexId = buildVertexIdMap(allKeys);

  const lines: string[] = [
    "# Workflow FSM",
    "",
    "Generated by **stubber-json** `explode`. This file is documentation only; it is **not** read on `implode`.",
    "",
    "## State diagram",
    "",
    "```mermaid",
    "stateDiagram-v2",
    "%% vertex declarations (quoted labels, unquoted ids on edges)",
  ];

  const declKeys = [...vertexId.keys()].sort();
  for (const sk of declKeys) {
    const id = vertexId.get(sk)!;
    const disp = escapeStateDisplayName(sk);
    // Trailing `;` helps when previews collapse newlines into one logical line.
    lines.push(`    state "${disp}" as ${id};`);
  }

  lines.push("%% transitions");

  if (start && vertexId.has(start)) {
    lines.push(`    [*] --> ${vertexId.get(start)};`);
  }

  const edgeStrings = new Set<string>();
  for (const e of edgeList) {
    const fromId = vertexId.get(e.from);
    const toId = vertexId.get(e.to);
    if (!fromId || !toId) continue;
    edgeStrings.add(`    ${fromId} --> ${toId} : ${e.label};`);
  }
  for (const row of [...edgeStrings].sort()) {
    lines.push(row);
  }

  lines.push("```", "");

  if (unknownActions.length > 0) {
    lines.push("## Unresolved action references", "");
    for (const u of unknownActions) {
      lines.push(`- \`${u}\``);
    }
    lines.push("");
  }

  lines.push("## States and allowed actions", "");

  for (const stateKey of Object.keys(states).sort()) {
    const st = states[stateKey];
    if (!isPlainObject(st)) continue;
    const allowed = Array.isArray(st.actions) ? st.actions.filter((x) => typeof x === "string") : [];
    const meta = isPlainObject(st.structure) ? (st.structure as JsonObject).meta : undefined;
    const done = isPlainObject(meta) && (meta as JsonObject).is_done === true;
    lines.push(`### \`${stateKey}\`${done ? " (terminal)" : ""}`, "");
    if (allowed.length === 0) {
      lines.push("_No actions listed for this state._", "");
    } else {
      for (const a of allowed) {
        lines.push(`- \`${a}\``);
      }
      lines.push("");
    }
  }

  return `${lines.join("\n")}\n`;
}
